### ISSUE TITLE
Very small typo

### ISSUE THREAD

**Issue by ismayc** [jnolis/banned-license-plates#2]
Just before the first non-license plate image in the blogpost at https://towardsdatascience.com/using-deep-learning-to-generate-offensive-license-plates-619b163ed937

<img width="706" alt="Screen Shot 2019-08-19 at 3 29 06 PM" src="https://user-images.githubusercontent.com/9215614/63303935-2ac5cd80-c296-11e9-83e2-8e08d2044872.png">

> then our small sequences would create a date set that looks like:

should be

> then our small sequences would create a data set that looks like:

**Comment by jnolis** [comment]
Fixed! That was hard to see!
